#!/bin/bash

set -euo pipefail

echo "--- :datadog: Recording step start time"

BUILDKITE_PLUGIN_DATADOG_STATS_STEP_START_TIME_MS=$(date +%s%3N)

export BUILDKITE_PLUGIN_DATADOG_STATS_STEP_START_TIME_MS

echo "Step started at ${BUILDKITE_PLUGIN_DATADOG_STATS_STEP_START_TIME_MS}"
