#!/bin/bash
set -euo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

. "$basedir/lib/get-tags.sh"
. "$basedir/lib/report-to-datadog.sh"

NOW=$(date +%s%3N)
START_TIME=$BUILDKITE_PLUGIN_DATADOG_STATS_COMMAND_START_TIME_MS
BASE_METRIC_PATH=${BUILDKITE_PLUGIN_DATADOG_STATS_METRIC_PREFIX:-buildkite.steps}

echo "--- :datadog: Recording command run time"

METRIC_NAME=${BASE_METRIC_PATH}.duration
METRIC_VALUE=$(($NOW-$START_TIME))
TAGS=$(getTags)

reportToDatadog $METRIC_NAME $METRIC_VALUE d "${TAGS}"
