#!/bin/bash

set -euo pipefail

echo "--- :git: Check for shallow clone override"
if [[ "${SHALLOW_CLONE:-false}" == "true" ]]; then
  echo "shallow clone override enabled"
  export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 1"
  export BUILDKITE_GIT_FETCH_FLAGS="-v --depth 1 --prune"
fi

echo "--- :datadog: Recording checkout start time"

BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS=$(date +%s%3N)

export BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS

echo "Checkout started at ${BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS}"
