#!/bin/bash

set -euo pipefail

echo "--- :git: Check for shallow clone"
echo "SHALLOW_CLONE = ${SHALLOW_CLONE:-false}"

echo "--- :datadog: Recording checkout start time"

BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS=$(date +%s%3N)

export BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS

echo "Checkout started at ${BUILDKITE_PLUGIN_DATADOG_STATS_CHECKOUT_START_TIME_MS}"
